num_steps_train: 5
num_steps: 1000
interval: 1
num_grids: [50, 50, 50, 0.02]
dt: "1/30"  # 30 FPS = 0.0333... seconds per frame
bound: 3
eps: 1e-7
skip_frame: 1
num_grippers: 1
preprocess_scale: 1.0
preprocess_with_table: True
n_particles: 1000
gripper_forcing: True
gripper_points: False
n_history: 2
uniform: False
